"""Added location_id to resource_instances

Revision ID: 07dc85c02bdb
Revises: d0be1e69dec4
Create Date: 2025-06-07 01:39:47.203636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07dc85c02bdb'
down_revision: Union[str, None] = 'd0be1e69dec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_instances', sa.Column('location_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_resource_instances_location_id'), 'resource_instances', ['location_id'], unique=False)
    op.create_foreign_key(None, 'resource_instances', 'location_entities', ['location_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource_instances', type_='foreignkey')
    op.drop_index(op.f('ix_resource_instances_location_id'), table_name='resource_instances')
    op.drop_column('resource_instances', 'location_id')
    # ### end Alembic commands ###
