"""Added Skil_definitions

Revision ID: 1882b33be14b
Revises: 13d294c01225
Create Date: 2025-05-09 13:05:01.733136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1882b33be14b'
down_revision: Union[str, None] = '13d294c01225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_definitions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='User-facing name of the skill.'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_level', sa.Integer(), server_default='100', nullable=False, comment='Maximum level attainable for this skill.'),
    sa.Column('themes', postgresql.ARRAY(sa.String(length=50)), nullable=True, comment='List of theme names/IDs where this skill is relevant.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_definitions_name'), 'skill_definitions', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_definitions_name'), table_name='skill_definitions')
    op.drop_table('skill_definitions')
    # ### end Alembic commands ###
