"""Added leader_id to settlments - FK character.id

Revision ID: 3932e126b100
Revises: 970eb6462248
Create Date: 2025-05-10 16:12:01.382687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3932e126b100'
down_revision: Union[str, None] = '970eb6462248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlements', sa.Column('leader_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'settlements', 'characters', ['leader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_column('settlements', 'leader_id')
    # ### end Alembic commands ###
