"""add_leader_relationship_to_settlement

Revision ID: 3ac01ef0cfe3
Revises: fix_character_traits_array
Create Date: 2025-05-18 01:22:30.988323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ac01ef0cfe3'
down_revision: Union[str, None] = 'fix_character_traits_array'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celestial_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_path', sa.Text(), nullable=False),
    sa.Column('actions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celestial_event_themes',
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('theme_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['celestial_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celestial_event_themes')
    op.drop_table('celestial_events')
    # ### end Alembic commands ###
