"""Changed FK Constraint to allow parent child with matching type_id

Revision ID: 5531cd41d4aa
Revises: 07dc85c02bdb
Create Date: 2025-06-09 03:13:45.010842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5531cd41d4aa'
down_revision: Union[str, None] = '07dc85c02bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
