"""Added location_faction_presence association table

Revision ID: 8988fbc5378d
Revises: 5531cd41d4aa
Create Date: 2025-06-09 12:10:47.785234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8988fbc5378d'
down_revision: Union[str, None] = '5531cd41d4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_faction_presence',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('faction_id', sa.UUID(), nullable=False),
    sa.Column('presence_pct', sa.Float(), nullable=False, comment='Percentage of presence'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['location_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'faction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_faction_presence')
    # ### end Alembic commands ###
