"""Added server_default to buildinginstance.id

Revision ID: 8b8035bcacd7
Revises: 80e932503c53
Create Date: 2025-05-11 20:12:37.938166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b8035bcacd7'
down_revision: Union[str, None] = '80e932503c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprint_stage_features',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('blueprint_stage_id', sa.UUID(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False, comment="Unique key for this feature within the stage, e.g., 'arrow_slits'."),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_professions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of profession IDs required to build this specific feature.'),
    sa.Column('additional_resource_costs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_duration_days', sa.Float(), nullable=True),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_stage_id'], ['blueprint_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_stage_id', 'feature_key', name='uq_stage_feature_key')
    )
    op.create_index(op.f('ix_blueprint_stage_features_blueprint_stage_id'), 'blueprint_stage_features', ['blueprint_stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blueprint_stage_features_blueprint_stage_id'), table_name='blueprint_stage_features')
    op.drop_table('blueprint_stage_features')
    # ### end Alembic commands ###
