"""Added world_id to characters table

Revision ID: 970eb6462248
Revises: 1882b33be14b
Create Date: 2025-05-10 14:47:48.173719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970eb6462248'
down_revision: Union[str, None] = '1882b33be14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('world_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_characters_world_id'), 'characters', ['world_id'], unique=False)
    op.create_foreign_key('fk_character_world_id', 'characters', 'worlds', ['world_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_character_world_id', 'characters', type_='foreignkey')
    op.drop_index(op.f('ix_characters_world_id'), table_name='characters')
    op.drop_column('characters', 'world_id')
    # ### end Alembic commands ###
