"""Added genre to themes

Revision ID: 9fbe3e39a9e1
Revises: fbb8882d1992
Create Date: 2025-06-03 02:45:19.194113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9fbe3e39a9e1'
down_revision: Union[str, None] = 'fbb8882d1992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    genre_enum = postgresql.ENUM(
        'fantasy',
        'sci_fi',
        'modern',
        'historical',
        'horror',
        'steampunk',
        'post_apocalyptic',
        'cyberpunk',
        'prehistoric',
        'victorian',
        name='genre'
    )
    genre_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('genre', sa.Enum('FANTASY', 'SCI_FI', 'MODERN', 'HISTORICAL', 'MYSTICAL', 'STEAMPUNK', 'POST_APOCALYPTIC', 'COSMIC', 'PREHISTORIC', 'VICTORIAN', name='genre'), nullable=True))
    op.alter_column('zones', 'world_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('zones', 'biome_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zones', 'biome_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('zones', 'world_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('themes', 'genre')
    # ### end Alembic commands ###
