"""Added building_upgrade_blueprint table

Revision ID: af29366a6cd6
Revises: 9e99edfb9c51
Create Date: 2025-05-12 21:38:24.490349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af29366a6cd6'
down_revision: Union[str, None] = '9e99edfb9c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_upgrade_blueprints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_blueprint_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_cost', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Resource costs. E.g., {'<resource_uuid_str>': 50, '<another_resource_uuid_str>': 20}"),
    sa.Column('profession_cost', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Profession costs (worker count). E.g., {'<profession_def_uuid_str>': 1}"),
    sa.Column('duration_days', sa.Integer(), server_default='1', nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_initial_choice', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_bldg_upg_bp_name', 'building_upgrade_blueprints', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bldg_upg_bp_name', table_name='building_upgrade_blueprints')
    op.drop_table('building_upgrade_blueprints')
    # ### end Alembic commands ###
