"""Added biomes table

Revision ID: b5e2d7a9c12f
Revises: af29366a6cd6
Create Date: 2025-05-15 10:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5e2d7a9c12f'
down_revision: Union[str, None] = 'af29366a6cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biomes',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('biome_id', sa.String(length=50), nullable=False, comment="Unique string identifier for the biome"),
        sa.Column('name', sa.String(length=100), nullable=False, comment="Display name of the biome"),
        sa.Column('display_name', sa.String(length=100), nullable=False, comment="User-friendly display name"),
        sa.Column('description', sa.Text(), nullable=True, comment="Detailed description of the biome"),
        sa.Column('base_movement_modifier', sa.Float(), nullable=False, default=1.0, 
                comment="Movement speed multiplier (1.0 = normal)"),
        sa.Column('danger_level_base', sa.Integer(), nullable=False, default=1, 
                comment="Base danger level (1-5)"),
        sa.Column('resource_types', postgresql.JSON(astext_type=sa.Text()), nullable=True, 
                comment="Dictionary of resource types and their abundance multipliers"),
        sa.Column('color_hex', sa.String(length=10), nullable=True, 
                comment="Hexadecimal color code for map display"),
        sa.Column('icon_path', sa.String(length=255), nullable=True,
                comment="Path to biome icon image"),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('biome_id')
    )

    # No longer adding seed data in the migration
    # Seed data should be handled by the import_biomes.py script instead
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biomes')
    # ### end Alembic commands ###