"""Added themes field to biomes

Revision ID: dff1ba0b778a
Revises: 4dc8f04c378e
Create Date: 2025-06-01 01:40:14.449079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff1ba0b778a'
down_revision: Union[str, None] = '4dc8f04c378e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biome_themes',
    sa.Column('biome_id', sa.UUID(), nullable=False, comment='Reference to biome'),
    sa.Column('theme_id', sa.UUID(), nullable=False, comment='Reference to theme'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this biome-theme association was created'),
    sa.ForeignKeyConstraint(['biome_id'], ['biomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('biome_id', 'theme_id'),
    comment='Association table linking biomes to themes (many-to-many)'
    )
    op.create_index('idx_biome_themes_biome_id', 'biome_themes', ['biome_id'], unique=False)
    op.create_index('idx_biome_themes_theme_id', 'biome_themes', ['theme_id'], unique=False)
    op.alter_column('settlements', 'zone_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('zones', 'world_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('zones', 'biome_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zones', 'biome_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('zones', 'world_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('settlements', 'zone_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_biome_themes_theme_id', table_name='biome_themes')
    op.drop_index('idx_biome_themes_biome_id', table_name='biome_themes')
    op.drop_table('biome_themes')
    # ### end Alembic commands ###
